name: main
on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [community, developer, enterprise]
        version: [ 8.6.1 ]
        include:
          - release: lts
            version:

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - uses: actions/checkout@v2

      - name: test test-${{ matrix.version != '' && format('{0}-{1}',matrix.version, matrix.release) || format('{0}', matrix.release) }}
        run: make test VERSION=${{ matrix.version != '' && format('{0}-{1}',matrix.version, matrix.release) || format('{0}', matrix.release) }}

  deploy-tags:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [community, developer, enterprise]
        version: [ 8.6.1 ]
        include:
          - release: lts
            version: 7.9.5
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mslipets/my-bloody-sonar:${{ github.ref }}
          build-args: FROM_TAG=${{ github.ref }}-${{ matrix.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-versions:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [community, developer, enterprise]
        version: [ 8.6.1 ]
        include:
          - release: lts
            version: 7.9.5
    if: github.event.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mslipets/my-bloody-sonar:latest
          build-args: FROM_TAG=${{ matrix.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
