name: main
on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [lts, community, developer, enterprise]
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - uses: actions/checkout@v2

      - name: test test-${{ matrix.version }}
        run: make test VERSION=${{ matrix.version }}

  deploy-tags:
    needs: test
    runs-on: ubuntu-latest
    strategy:
          matrix:
            version: [lts, community, developer, enterprise]

    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mslipets/my-bloody-sonar:${{ github.ref }}
          build-args:
           - FROM_TAG: ${{ github.ref }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-versions:
    needs: test
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mslipets/my-bloody-sonar:latest
          build-args:
           - FROM_TAG: latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
